name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */12 * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Npm install
      run: |
        npm install
    - name: Update README
      env:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      run: |-
        node build_readme.js
    - name: Commit and push if changed
      run: |-
        git config --global user.email "disflyer123@gmail.com"
        git config --global user.name "disflyer-bot"
        git pull origin main
        git diff
        git add -A
        git commit -m "Updated content" || exit 0
        git push
